safe:        false
port:        4000
baseurl:     /
url:         
author:      Rob Bernabé
description: "Hi, I'm Rob. I'm a 32 year old software and platform engineer living in NYC, where I work for the financial services startup PayPerks. I love solving interesting problems and building useful things."

exclude:
    - Gemfile
    - Gemfile.lock
    - config.rb
    - Rakefile

#source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true
markdown:    kramdown
permalink:   /posts/:year/:month/:day/:title/

maruku:
  use_tex:    false
  use_divs:   false

tag_page_layout: tag_page
tag_page_dir: tag
